### ISSUE TITLE
Glioma Classification of PET images

### ISSUE THREAD

**Issue by Hogandr** [NUS-Tim/DEMS#1]
Hey @NUS-Tim ,
I think your paper is very interesting. I would like to use a similar procedure for glioma classification. As I only have 150 patients in total, there is a big risk of overfitting. Do you happen to have any experience with your methodology with PET data and/or classification?
I would be very happy about your input!!!
Greetings
Hagen

**Comment by NUS-Tim** [comment]
Hi, this approach is designed for segmentation. For your concerns, I would suggest you do some offline augmentation ahead of training.
